### ISSUE TITLE
Not working for Android build?

### ISSUE THREAD

**Issue by Snail921** [simplestargame/UniversalRP-VR-MosaicShader#1]
Works fine in the unity editor but I cannot figure out proper setting for this to make it work on Android build.
The material is rendered in grey or not rendered at all.
It would be great if we can use this with your asset, the Simple Interactive Water for URP VR which I bout from the asset store...
Any suggestion?

**Comment by simplestargame** [comment]
Replace "Texture 2D" (_CameraOpaqueTexture parameter) node  to "scene color" node. That texture seemed to be unsupported on Android.

**Comment by Snail921** [comment]
> Replace "Texture 2D" (_CameraOpaqueTexture parameter) node to "scene color" node. That texture seemed to be unsupported on Android.

Wow, I didn't know how the scene color node works. That is such a valuable information!
Now it has been simplified and ended up like this. Works fine.
[URPMosaic](https://imgur.com/a/DgmejjF)
Thank you so much for your advice!
